config/routes.rb
Rails.application.routes.draw do

  get 'auth/wechat/callback' => 'users#omniauth_callbacks'

  namespace :m do
    get 'home/index'
    get 'home/water'

    get 'fairy_coins_pay' => 'pay#fairy_coins_pay'
    post 'wx_pay' => 'pay#wx_pay'
    post 'wx_notify' => 'pay#wx_notify'

    resources :crowdfundings
    #resources :coupons, only: [:new, :create]
    #resources :awards, only: [:index, :show]
    #resources :lucky_draws, only: [:index, :create] do
    #  collection do
    #    get :draw
    #    get :list
    #  end
    #end
    resources :user_lockers, only: [:new, :create]
    resources :membership_cards, only: [:index, :show, :new]
    resources :user_membership_cards, only: [:index, :show, :create] do
      member do
        get :check
        post :checkin
      end
    end
    resources :deposits, only: [:index, :show, :new, :create]
    resources :orders, only: [:index, :show, :create]
    resources :order_tickets, only: [] do
      member do
        get :check
        post :checkin
      end
    end
    resources :tickets, only: [:index, :show]
    resources :shopping_carts, only: [:index, :destroy] do
      collection do
        get :add
      end
    end
    resources :users do
      collection do
        get :profile
        get :foregift
      end
    end
    resources :lessons, only: [:index, :show] do
      resources :students, only: [:new, :create]
    end
    resources :students, only: [:index, :show]
  end

  get 'home/index'

  namespace :admin do
    scope "/park" do
      resources :orders, only: [:index, :show, :create, :destroy]
      resources :order_tickets, only: [:show, :edit, :update]
      resources :coupons
      resources :awards
      resources :user_lockers, only: [:index] do
        member do
          get :back
        end
      end
      resources :lockers
      resources :membership_cards do
        resources :user_membership_cards
      end
      resources :users, only: [:index]
      resources :tickets do
        collection do
          get :sell
        end
      end
    end
    scope '/lesson' do
      resources :daylines do
        member do
          get :notice
          get :congratulate
        end
      end
      resources :timelines
      resources :lessons do
        member do
          get :subitems
        end
      end
      resources :students
    end
    scope '/store' do
      resources :products
      resources :sales_lists
    end
    scope '/system' do
      resources :admins
      resources :roles
      resources :crowdfundings
    end
    
    resources :sessions, only: [:new, :create, :destroy]
    
    resources :games do
      member do
        get :lot
        get :lock
      end
      resources :playeds do
        resources :techstats, only: [:index, :create, :edit, :update]
      end
      resources :game_teams, only: [:index, :new, :create, :edit, :update]
    end

    get 'dashboard/index'
    root "dashboard#index"
  end

  root "home#index"
end

app/models/order.rb
class Order < ApplicationRecord
    enum status: [:pending, :checkouted, :completed]

    has_many :order_tickets, :dependent => :destroy
    belongs_to :user

    def total_price
        total_price = 0
        self.order_tickets.each do |order_ticket|
            total_price += order_ticket.ticket.price
        end
        total_price
    end
    
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  def create
    begin
      @order = Order.create!(
                    sn: DateTime.parse(Time.now.iso8601).strftime('%Y%m%d%H%M%S') + rand(999).to_s,
                    status: :completed)
      params["tickets"].each do |i|
        puts i
        OrderTicket.create!(order_id: @order.id, ticket_id: i.to_i, serial_number: 'TN' + DateTime.parse(Time.now.iso8601).strftime('%Y%m%d%H%M%S') + rand(999).to_s)
        puts i
      end
    rescue
      redirect_to sell_admin_tickets_path, notice: "出售失败！" and return
    end
    redirect_to sell_admin_tickets_path, notice: "出售成功！"
  end

  def index
    @orders = Order.all.order("created_at DESC").paginate(:page => params[:page])
  end

  def show
    @order = Order.find(params[:id])
  end

  def destroy
    @order = Order.find params[:id]
    @order.destroy
    redirect_to admin_orders_path
  end
end

app/controllers/m/orders_controller.rb
class M::OrdersController < MobileController
  def index
    @orders = current_user.orders.order("created_at DESC")
  end

  def show
    @order = Order.find params[:id]
  end

  def create
    @shopping_carts = current_user.shopping_carts
    if @shopping_carts.count <= 0
      redirect_to m_shopping_carts_path, notice: '购物车为空.' and return
    end
    begin
      @order = Order.create!(user_id: current_user.id, sn: DateTime.parse(Time.now.iso8601).strftime('%Y%m%d%H%M%S') + rand(999).to_s, status: :pending)
      @shopping_carts.each do |shopping_cart|
        order_ticket = OrderTicket.create!(order_id: @order.id, ticket_id: shopping_cart.ticket_id, serial_number: 'TN' + DateTime.parse(Time.now.iso8601).strftime('%Y%m%d%H%M%S') + rand(999).to_s)
        shopping_cart.destroy
      end
      redirect_to m_order_path(@order), notice: "订单生成成功."
    rescue
      redirect_to m_shopping_carts_path, notice: "生成订单失败."
    end
  end
  
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/m/orders_helper.rb
module M::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="card">
  <div class="card-body card-padding">
    <table class="table">
        <thead>
            <tr>
                <th>订单编号</th>
                <th>订单总价</th>
                <th>用户</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
            <tr>
                <th scope="row"><%= order.sn %></th>
                <td><%= order.total_price %></td>
                <td><%= order.user.nickname %></td>
                <td>
                    <%= i18n_enum order, :status %>
                </td>
                <td>
                    <%= link_to "查看", admin_order_path(order) %>
                    <%= link_to '删除', admin_order_path(order), method: :delete %>
                </td>
            </tr>
        <% end %>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">
                    <%= will_paginate @orders %>
                </td>
            </tr>
        </tfoot>
    </table>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="card">
  <div class="card-body card-padding">
    <table class="table">
        <thead>
            <tr>
                <th colspan="3">订单号：<%= @order.sn %></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td>门票</td>
                <td>价格</td>
                <td>票号</td>
                <td>已入场</td>
                <td>操作</td>
            </tr>
        <% @order.order_tickets.each do |order_ticket| %>
            <tr>
                <td><i class="zmdi zmdi-ticket-star"></i></i></td>
                <td scope="row"><%= order_ticket.ticket.name %></td>
                <td><%= order_ticket.ticket.price %></td>
                <td><%= order_ticket.serial_number %></td>
                <td><%= order_ticket.used %></td>
                <td>
                    <%= link_to "查看", admin_order_ticket_path(order_ticket) %>
                    <%= link_to "修改", edit_admin_order_ticket_path(order_ticket) %>
                </td>
            </tr>
        <% end %>
        <tfoot>
            <td colspan="6">总价 ¥<%= @order.total_price %></td>
        </tfoot>
    </table>
  </div>
</div>