config/routes.rb
Rails.application.routes.draw do

  get 'auth/wechat/callback' => 'users#omniauth_callbacks'

  namespace :m do
    get 'home/index'
    get 'home/water'

    get 'fairy_coins_pay' => 'pay#fairy_coins_pay'
    post 'wx_pay' => 'pay#wx_pay'
    post 'wx_notify' => 'pay#wx_notify'

    resources :crowdfundings
    #resources :coupons, only: [:new, :create]
    #resources :awards, only: [:index, :show]
    #resources :lucky_draws, only: [:index, :create] do
    #  collection do
    #    get :draw
    #    get :list
    #  end
    #end
    resources :user_lockers, only: [:new, :create]
    resources :membership_cards, only: [:index, :show, :new]
    resources :user_membership_cards, only: [:index, :show, :create] do
      member do
        get :check
        post :checkin
      end
    end
    resources :deposits, only: [:index, :show, :new, :create]
    resources :orders, only: [:index, :show, :create]
    resources :order_tickets, only: [] do
      member do
        get :check
        post :checkin
      end
    end
    resources :tickets, only: [:index, :show]
    resources :shopping_carts, only: [:index, :destroy] do
      collection do
        get :add
      end
    end
    resources :users do
      collection do
        get :profile
        get :foregift
      end
    end
    resources :lessons, only: [:index, :show] do
      resources :students, only: [:new, :create]
    end
    resources :students, only: [:index, :show]
  end

  get 'home/index'

  namespace :admin do
    scope "/park" do
      resources :orders, only: [:index, :show, :create, :destroy]
      resources :order_tickets, only: [:show, :edit, :update]
      resources :coupons
      resources :awards
      resources :user_lockers, only: [:index] do
        member do
          get :back
        end
      end
      resources :lockers
      resources :membership_cards do
        resources :user_membership_cards
      end
      resources :users, only: [:index]
      resources :tickets do
        collection do
          get :sell
        end
      end
    end
    scope '/lesson' do
      resources :daylines do
        member do
          get :notice
          get :congratulate
        end
      end
      resources :timelines
      resources :lessons do
        member do
          get :subitems
        end
      end
      resources :students
    end
    scope '/store' do
      resources :products
      resources :sales_lists
    end
    scope '/system' do
      resources :admins
      resources :roles
      resources :crowdfundings
    end
    
    resources :sessions, only: [:new, :create, :destroy]
    
    resources :games do
      member do
        get :lot
        get :lock
      end
      resources :playeds do
        resources :techstats, only: [:index, :create, :edit, :update]
      end
      resources :game_teams, only: [:index, :new, :create, :edit, :update]
    end

    get 'dashboard/index'
    root "dashboard#index"
  end

  root "home#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password

  belongs_to :role, optional: true
  has_many :permissions, through: :role
end

app/models/award.rb
class Award < ApplicationRecord
    has_many :lucky_draws
end

app/models/coupon.rb
class Coupon < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :ticket
end

app/models/crowdfunding.rb
class Crowdfunding < ApplicationRecord
    has_many :user_crowdfundings
end

app/models/dayline.rb
class Dayline < ApplicationRecord
    has_many :students
    belongs_to :lesson
end

app/models/deposit.rb
class Deposit < ApplicationRecord
    belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    has_many :students
    has_many :daylines
    has_many :timelines
end

app/models/locker.rb
class Locker < ApplicationRecord
    enum state: [:used, :unused, :maintained]
    
    has_many :user_lockers
end

app/models/lucky_draw.rb
class LuckyDraw < ApplicationRecord
    belongs_to :user
    belongs_to :award, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
    enum status: [:pending, :checkouted, :completed]

    has_many :order_tickets, :dependent => :destroy
    belongs_to :user

    def total_price
        total_price = 0
        self.order_tickets.each do |order_ticket|
            total_price += order_ticket.ticket.price
        end
        total_price
    end
    
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :role
  has_many :admins, through: :role

  validates :resource, presence: true
  validates :action, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :sales_list_products
end

app/models/role.rb
class Role < ApplicationRecord
  RESERVED = %w(admin)

  has_many :permissions, dependent: :destroy
  has_many :admins

  validates :name, presence: true, uniqueness: true

  scope :editable, -> { where.not(name: RESERVED ) }
end

app/models/sales_list.rb
class SalesList < ApplicationRecord
    has_many :sales_list_products

    def total_price
        total_price = 0
        self.sales_list_products.each do |sales_list_product|
            total_price += sales_list_product.product.price
        end
        total_price
    end
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
  load! if Rails.env.development?
end

app/models/student.rb
class Student < ApplicationRecord
    enum status: [:pending, :checkouted, :completed, :canceled]

    belongs_to :lesson
    belongs_to :user, optional: true
    belongs_to :dayline
    belongs_to :timeline
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :order_tickets
  has_many :shopping_carts
  has_many :coupons
end

app/models/timeline.rb
class Timeline < ApplicationRecord
    has_many :students
    belongs_to :lesson
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  extend Enumerize  #pending 新建状态  cooking烹饪状态  finished完成状态  canceled取消
  enumerize :position,     in: [:PG, :SG, :SF, :PF, :C], default: :SF

  enum sex: [:unknown, :female, :male]

  mount_uploader :avatar, UserAvatarUploader
  attr_accessor :uploader_secure_token

  has_one :my_team, class_name: "Team"
  belongs_to :team
  has_many :techstats
  has_many :shopping_carts
  has_many :orders
  has_many :students
  has_many :deposits
  has_many :user_membership_cards
  has_many :user_lockers
  has_many :lucky_draws
  has_many :coupons
  has_many :user_crowdfundings

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.nickname = auth.info.nickname
      user.sex = auth.info.sex
      user.wechat_avatar = auth.info.headimgurl
      user.open_id = auth.info.openid
    end
  end
end

app/models/user_locker.rb
class UserLocker < ApplicationRecord
    belongs_to :user
    belongs_to :locker
end

app/controllers/admin/crowdfundings_controller.rb
class Admin::CrowdfundingsController < AdminController
  before_action :set_crowdfunding, only: [:show, :edit, :update, :destroy]

  def index
    @crowdfundings = Crowdfunding.all.order("created_at ASC").paginate(:page => params[:page])
  end

  def show
  end

  def new
    @crowdfunding = Crowdfunding.new
  end

  def create
    @crowdfunding = Crowdfunding.new crowdfunding_params
    if @crowdfunding.save
      redirect_to admin_crowdfundings_path
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @crowdfunding.update crowdfunding_params
      redirect_to admin_crowdfundings_path
    else
      render :edit
    end
  end

  def destroy
    @crowdfunding.destroy
    redirect_to admin_crowdfundings_path
  end
  
  private

  def set_crowdfunding
    @crowdfunding = Crowdfunding.find(params[:id])
  end

  def crowdfunding_params
    params.require(:crowdfunding).permit(:subject, :fee, :desc)
  end
end

app/controllers/m/crowdfundings_controller.rb
class M::CrowdfundingsController < MobileController
  def index
    @crowdfundings = Crowdfunding.all.order("fee ASC")
  end

  def show
    @crowdfunding = Crowdfunding.find params[:id]
  end
end

app/helpers/admin/crowdfundings_helper.rb
module Admin::CrowdfundingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/m/crowdfundings_helper.rb
module M::CrowdfundingsHelper
end

app/views/admin/crowdfundings/_form.html.erb
<%= form_for [:admin, @crowdfunding], html: { class: "form-horizontal" } do |f| %>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">众筹项目</label>
        <div class="col-sm-10">
            <%= f.text_field :subject, class: "form-control", placeholder: "众筹项目" %>
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">费用</label>
        <div class="col-sm-10">
            <%= f.number_field :fee, class: "form-control", placeholder: "费用" %>
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">描述</label>
        <div class="col-sm-10">
            <%= f.text_field :desc, class: "form-control", placeholder: "描述" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">保存</button>
        </div>
    </div>
<% end %>

app/views/admin/crowdfundings/edit.html.erb
<div class="card">
  <div class="card-body card-padding">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/crowdfundings/index.html.erb
<div class="card">
  <div class="card-body card-padding">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>众筹项目</th>
                <th>费用</th>
                <th>描述</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        <% @crowdfundings.each do |crowdfunding| %>
            <tr>
                <th scope="row"><%= crowdfunding.id %></th>
                <td><%= crowdfunding.subject %></td>
                <td><%= crowdfunding.fee %></td>
                <td><%= crowdfunding.desc %></td>
                <td>
                    <%= link_to "修改", edit_admin_crowdfunding_path(crowdfunding) %>
                    <%= link_to '删除', admin_crowdfunding_path(crowdfunding), method: :delete %>
                </td>
            </tr>
        <% end %>
    </table>
  </div>
</div>

app/views/admin/crowdfundings/new.html.erb
<div class="card">
  <div class="card-body card-padding">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/crowdfundings/show.html.erb
<h1>Admin::Crowdfundings#show</h1>
<p>Find me in app/views/admin/crowdfundings/show.html.erb</p>