config/routes.rb
Rails.application.routes.draw do

  get 'auth/wechat/callback' => 'users#omniauth_callbacks'

  namespace :m do
    get 'home/index'
    get 'home/water'

    get 'fairy_coins_pay' => 'pay#fairy_coins_pay'
    post 'wx_pay' => 'pay#wx_pay'
    post 'wx_notify' => 'pay#wx_notify'

    resources :crowdfundings
    #resources :coupons, only: [:new, :create]
    #resources :awards, only: [:index, :show]
    #resources :lucky_draws, only: [:index, :create] do
    #  collection do
    #    get :draw
    #    get :list
    #  end
    #end
    resources :user_lockers, only: [:new, :create]
    resources :membership_cards, only: [:index, :show, :new]
    resources :user_membership_cards, only: [:index, :show, :create] do
      member do
        get :check
        post :checkin
      end
    end
    resources :deposits, only: [:index, :show, :new, :create]
    resources :orders, only: [:index, :show, :create]
    resources :order_tickets, only: [] do
      member do
        get :check
        post :checkin
      end
    end
    resources :tickets, only: [:index, :show]
    resources :shopping_carts, only: [:index, :destroy] do
      collection do
        get :add
      end
    end
    resources :users do
      collection do
        get :profile
        get :foregift
      end
    end
    resources :lessons, only: [:index, :show] do
      resources :students, only: [:new, :create]
    end
    resources :students, only: [:index, :show]
  end

  get 'home/index'

  namespace :admin do
    scope "/park" do
      resources :orders, only: [:index, :show, :create, :destroy]
      resources :order_tickets, only: [:show, :edit, :update]
      resources :coupons
      resources :awards
      resources :user_lockers, only: [:index] do
        member do
          get :back
        end
      end
      resources :lockers
      resources :membership_cards do
        resources :user_membership_cards
      end
      resources :users, only: [:index]
      resources :tickets do
        collection do
          get :sell
        end
      end
    end
    scope '/lesson' do
      resources :daylines do
        member do
          get :notice
          get :congratulate
        end
      end
      resources :timelines
      resources :lessons do
        member do
          get :subitems
        end
      end
      resources :students
    end
    scope '/store' do
      resources :products
      resources :sales_lists
    end
    scope '/system' do
      resources :admins
      resources :roles
      resources :crowdfundings
    end
    
    resources :sessions, only: [:new, :create, :destroy]
    
    resources :games do
      member do
        get :lot
        get :lock
      end
      resources :playeds do
        resources :techstats, only: [:index, :create, :edit, :update]
      end
      resources :game_teams, only: [:index, :new, :create, :edit, :update]
    end

    get 'dashboard/index'
    root "dashboard#index"
  end

  root "home#index"
end

app/models/user_membership_card.rb
class UserMembershipCard < ApplicationRecord
    enum status: [:pending, :checkouted, :disabled]

    belongs_to :membership_card
    belongs_to :user
end

app/controllers/admin/user_membership_cards_controller.rb
class Admin::UserMembershipCardsController < AdminController
  before_action :set_membership_card, only: [:index, :edit, :update, :destroy]
  before_action :set_user_membership_card, only: [:show, :edit, :update, :destroy]
  
  def index
    @user_membership_cards = @membership_card.user_membership_cards.order("created_at DESC").paginate(:page => params[:page])
  end

  def show
  end

  def edit
  end

  def update
    if @user_membership_card.update user_membership_card_params
      redirect_to admin_membership_card_user_membership_card_path(@membership_card, @user_membership_card), notice: "更新成功！"
    else
      redirect_to admin_membership_card_user_membership_card_path(@membership_card, @user_membership_card), notice: "更新失败！"
    end
  end

  def destroy
    @user_membership_card.destroy
    redirect_to admin_membership_card_user_membership_cards_path(@membership_card), notice: "删除成功！"
  end

  private

  def set_membership_card
    @membership_card = MembershipCard.find params[:membership_card_id]
  end

  def set_user_membership_card
    @user_membership_card = UserMembershipCard.find params[:id]
  end

  def user_membership_card_params
    params.require(:user_membership_card).permit(:status, :count)
  end
  
end

app/controllers/m/awards_controller.rb
class M::AwardsController < MobileController
  def index
    @awards = Award.all.order("id ASC")
  end

  def show
    @award = Award.find params[:id]
  end
end

app/controllers/m/coupons_controller.rb
class M::CouponsController < MobileController
    def new
        @coupon = Coupon.new
    end
    
    def create
        coupon = Coupon.find_by_serial_number params[:coupon][:serial_number]
        if coupon.blank?
            redirect_to new_m_coupon_path and return
        end
        begin
            @order = Order.create!(user_id: current_user.id, sn: DateTime.parse(Time.now.iso8601).strftime('%Y%m%d%H%M%S') + rand(999).to_s, status: :checkouted)
            order_ticket = OrderTicket.create!(order_id: @order.id, ticket_id: coupon.ticket_id, serial_number: 'TN' + DateTime.parse(Time.now.iso8601).strftime('%Y%m%d%H%M%S') + rand(999).to_s)
            redirect_to m_order_path(@order), notice: "订单生成成功."
        rescue
            redirect_to new_m_coupon_path, notice: "兑现奖品失败."
        end
    end

    private

    def coupon_params
        params.require(:coupon).permit(:serial_number)
    end
end

app/controllers/m/crowdfundings_controller.rb
class M::CrowdfundingsController < MobileController
  def index
    @crowdfundings = Crowdfunding.all.order("fee ASC")
  end

  def show
    @crowdfunding = Crowdfunding.find params[:id]
  end
end

app/controllers/m/deposits_controller.rb
class M::DepositsController < MobileController
  def index
    @deposits = current_user.deposits.order("created_at DESC")
  end

  def show
    @deposit = Deposit.find params[:id]
  end

  def new
    @deposit = Deposit.new
  end

  def create
    @deposit = Deposit.new deposit_params
    @deposit.trade_no = 'DN' + DateTime.parse(Time.now.iso8601).strftime('%Y%m%d%H%M%S') + rand(999).to_s
    @deposit.user_id = current_user.id
    if @deposit.save
      redirect_to m_deposit_path(@deposit)
    else
      render :new
    end
  end

  private

  def deposit_params
    params.require(:deposit).permit(:fee)
  end
  
end

app/controllers/m/home_controller.rb
class M::HomeController < MobileController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/m/lessons_controller.rb
class M::LessonsController < MobileController
  def index
    @lessons = Lesson.all.order("created_at DESC")
  end

  def show
    @lesson = Lesson.find params[:id]
  end
end

app/controllers/m/lucky_draws_controller.rb
class M::LuckyDrawsController < MobileController
  def index
  end

  def list
    @lucky_draws = current_user.lucky_draws.order("created_at DESC")
  end

  def create
    @lucky_draw = LuckyDraw.new lucky_draw_params
    if @lucky_draw.save
      render json: { result: true, msg: "获得一次抽奖机会" }
    else
      render json: { result: false, msg: "没有获得抽奖机会" }
    end
  end
  
  def draw
    @lucky_draw = current_user.lucky_draws.where(drawed: false).first
    if @lucky_draw.blank?
      redirect_to m_lucky_draws_path and return
    end
    # 抽奖
    @lucky = false
    temp_number = rand
    Award.all.order("rate ASC").each do |award|
      if temp_number < award.rate
        begin
          @lucky_draw.update_attributes(award_id: award.id, drawed: true, drawed_at: Time.now)
          @lucky = true
          eval award.code
        rescue Exception => e
          Rails.logger.error e.backtrace.join("\n")
        end
        break
      end
    end
    if not @lucky
      @lucky_draw.update_attributes(drawed: true, drawed_at: Time.now)
    end
  end

  private

  def lucky_draw_params
    params.require(:lucky_draw).permit(:user_id, :award_id, :received)
  end
end

app/controllers/m/membership_cards_controller.rb
class M::MembershipCardsController < MobileController
  def index
    @user_membership_cards = current_user.user_membership_cards.order("created_at DESC")
  end

  def new
    @membership_cards = MembershipCard.all.order("created_at ASC")
  end
end

app/controllers/m/order_tickets_controller.rb
class M::OrderTicketsController < MobileController
  def check
    @order_ticket = OrderTicket.find params[:id]
  end

  def checkin
    @order_ticket = OrderTicket.find params[:id]
    @checked = false
    unless params[:safe_code].blank?
      if params[:safe_code] == "bf007"
        @checked = true if @order_ticket.update_attributes(used: true)
      end
    end
  end
end

app/controllers/m/orders_controller.rb
class M::OrdersController < MobileController
  def index
    @orders = current_user.orders.order("created_at DESC")
  end

  def show
    @order = Order.find params[:id]
  end

  def create
    @shopping_carts = current_user.shopping_carts
    if @shopping_carts.count <= 0
      redirect_to m_shopping_carts_path, notice: '购物车为空.' and return
    end
    begin
      @order = Order.create!(user_id: current_user.id, sn: DateTime.parse(Time.now.iso8601).strftime('%Y%m%d%H%M%S') + rand(999).to_s, status: :pending)
      @shopping_carts.each do |shopping_cart|
        order_ticket = OrderTicket.create!(order_id: @order.id, ticket_id: shopping_cart.ticket_id, serial_number: 'TN' + DateTime.parse(Time.now.iso8601).strftime('%Y%m%d%H%M%S') + rand(999).to_s)
        shopping_cart.destroy
      end
      redirect_to m_order_path(@order), notice: "订单生成成功."
    rescue
      redirect_to m_shopping_carts_path, notice: "生成订单失败."
    end
  end
  
end

app/controllers/m/pay_controller.rb
class M::PayController < MobileController
  before_action :authenticate_user!, except: [:wx_notify]
  skip_before_action :verify_authenticity_token, only: [:wx_notify]

  def fairy_coins_pay
    params[:trade_no] ||= ""
    order = Order.find_by_sn params[:trade_no]
    redirect_to m_orders_path and return if order.blank?
    total_fee = order.total_price
    redirect_to m_order_path(order) and return if total_fee.to_i > current_user.fairy_coins.to_i
    begin
      order.update_attributes!(status: :checkouted)
      current_user.update_attributes!(fairy_coins: current_user.fairy_coins.to_i - total_fee.to_i)
      redirect_to m_order_path(order)
    rescue
      redirect_to m_order_path(order)
    end
  end

  def wx_pay
    if params[:id].blank? || params[:name].blank?
      render json: { error: 'id & name is nil' }
      return
    end
    
    if params[:name].downcase == 'order'
      order = Order.find(params[:id])
      body = '蓝精灵水上乐园-门票'
      out_trade_no = order.sn
      total_fee = order.total_price.to_i * 100
      attach = "order"
    elsif params[:name].downcase == 'student'
      student = Student.find(params[:id])
      body = "蓝精灵水上乐园-#{student.lesson.subject}培训费"
      out_trade_no = student.trade_no
      total_fee = student.lesson.price.to_i * 100
      attach = "student"
    elsif params[:name].downcase == 'deposit'
      deposit = Deposit.find(params[:id])
      body = "蓝精灵水上乐园-充值"
      out_trade_no = deposit.trade_no
      total_fee = deposit.fee.to_i * 100
      attach = "deposit"
    elsif params[:name].downcase == 'usermembershipcard'
      user_membership_card = UserMembershipCard.find(params[:id])
      body = "蓝精灵水上乐园-会员卡"
      out_trade_no = user_membership_card.trade_no
      total_fee = user_membership_card.membership_card.fee.to_i * 100
      attach = "usermembershipcard"
    elsif params[:name].downcase == 'foregift'
      user = User.find params[:id]
      body = "蓝精灵水上乐园-储物柜押金"
      out_trade_no = "#{user.id}_FG" + DateTime.parse(Time.now.iso8601).strftime('%Y%m%d%H%M%S') + rand(999).to_s
      total_fee = 2000
      attach = "foregift"
    end
    
    pay_params = {
      body: body,
      out_trade_no: out_trade_no,
      total_fee: total_fee,
      spbill_create_ip: request.remote_ip,
      notify_url: Figaro.env.wechat_pay_notify_url,
      trade_type: 'JSAPI',
      openid: current_user.uid,
      attach: attach
    }

    prepay_result = WxPay::Service.invoke_unifiedorder(pay_params)
    if prepay_result.success?
      js_pay_params = {
        prepayid: prepay_result['prepay_id'],
        noncestr: prepay_result['nonce_str']
      }
      pay_params = WxPay::Service.generate_js_pay_req js_pay_params
      logger.info pay_params
      render json: pay_params
    else
      logger.error prepay_result['return_msg']
      render json: prepay_result
    end
  end

  def wx_notify
    result = Hash.from_xml(request.body.read)['xml']
    if WxPay::Sign.verify?(result)
      if result["attach"] == "order"
        order = Order.find_by_sn(result["out_trade_no"])
        order.update_attributes(status: :checkouted)
      elsif result["attach"] == 'student'
        student = Student.find_by_trade_no(result["out_trade_no"])
        student.update_attributes(status: :checkouted, paid_in: student.lesson.price.to_i)
      elsif result["attach"] == 'deposit'
        deposit = Deposit.find_by_trade_no(result["out_trade_no"])
        deposit.update_attributes(checkouted: true)
        user = deposit.user
        award_fee = (deposit.fee.to_i / 100).to_i * 30
        user.update_attributes(fairy_coins: user.fairy_coins.to_i + deposit.fee.to_i + award_fee)
      elsif result["attach"] == 'usermembershipcard'
        user_membership_card = UserMembershipCard.find_by_trade_no(result["out_trade_no"])
        user_membership_card.update_attributes(status: :checkouted)
        # 设置实效日期
      elsif result["attach"] == 'foregift'
        _id = result["out_trade_no"].split("_")[0]
        user = User.find _id
        user.update_attributes(foregift: user.foregift.to_i + 20)
      end
      render xml: { return_code: 'SUCCESS', return_msg: 'OK' }.to_xml(root: 'xml', dasherize: false)
    else
      render xml: { return_code: 'FAIL', return_msg: 'Signature Error' }.to_xml(root: 'xml', dasherize: false)
    end
  end
end

app/controllers/m/shopping_carts_controller.rb
class M::ShoppingCartsController < MobileController
  def index
    @shopping_carts = current_user.shopping_carts
  end

  def add
    @shopping_cart = ShoppingCart.new
    @shopping_cart.user_id = current_user.id
    @shopping_cart.ticket_id = params[:ticket_id]
    @result = @shopping_cart.save
  end
  
  def udpate
  end
  
  def destroy
    @shopping_cart = ShoppingCart.find params[:id]
    @shopping_cart.destroy
    redirect_to m_shopping_carts_path
  end
  
end

app/controllers/m/students_controller.rb
class M::StudentsController < MobileController
  def index
    @students = current_user.students
  end
  
  def show
    @student = Student.find params[:id]
  end
  
  def new
    @lesson = Lesson.find params[:lesson_id]
    @student = Student.new
  end

  def create
    @lesson = Lesson.find params[:lesson_id]
    @student = Student.new student_params
    @student.status = :pending
    @student.lesson_id = @lesson.id
    @student.user_id = current_user.id
    @student.trade_no = 'STN' + rand(999).to_s + DateTime.parse(Time.now.iso8601).strftime('%Y%m%d%H%M%S')
    if @student.save
      redirect_to m_student_path(@student)
    else
      render :new
    end
  end
  
  private

  def student_params
    params.require(:student).permit(:name, :avatar, :phone, :height, :age, :dayline_id, :timeline_id)
  end
  
end

app/controllers/m/swiming_lessons_controller.rb
class M::StudentsController < MobileController
  def new
    @student = Student.new
  end

  def create
    @student = Student.new params_student
    @student.status = :pending
    if @student.save
      redirect_to m_student(@student)
    else
      render :new
    end
  end
  
  private

  def params_student
    params.require(:student).permit(:name, :avatar, :phone, :height, :age)
  end
  
end

app/controllers/m/tickets_controller.rb
class M::TicketsController < MobileController
  def index
    @tickets = Ticket.where(enabled: :true).order("created_at DESC")
  end

  def show
    @ticket = Ticket.find(params[:id])
  end
end

app/controllers/m/user_lockers_controller.rb
class M::UserLockersController < MobileController
  def new
    @user_locker = UserLocker.where(user_id: current_user.id, used: true).first
  end

  def create
    if current_user.foregift.to_i < 20
      redirect_to new_m_user_locker_path and return
    end
    locker = Locker.where(state: :unused).first
    if locker.blank?
      redirect_to new_m_user_locker_path and return
    end
    user_locker = UserLocker.new
    user_locker.user_id = current_user.id
    user_locker.locker_id = locker.id
    user_locker.used = true
    if user_locker.save
      locker.update_attributes(state: :used)
      redirect_to new_m_user_locker_path
    else
      redirect_to new_m_user_locker_path
    end
  end
  
end

app/controllers/m/users_controller.rb
class M::UsersController < MobileController
  def profile
  end

  def foregift
  end
  
end

app/views/m/user_membership_cards/check.html.erb
<%= form_tag(checkin_m_user_membership_card_path(@user_membership_card), { class: "form-horizontal" }) do %>
  <div class="mdui-textfield mdui-textfield-floating-label">
    <label class="mdui-textfield-label">安全码</label>
    <%= text_field_tag :safe_code, "", class: "mdui-textfield-input" %>
  </div>
  <%= submit_tag "验票", class: "mdui-btn mdui-btn-block mdui-color-pink-accent mdui-ripple" %>   
<% end %>

app/views/m/user_membership_cards/checkin.html.erb
<div class="mdui-container">
  <div class="mdui-row-xs-1">
    <div class="mdui-col">
    <% if @checked %>
      <div class="mdui-center">
        <div class="mdui-chip mdui-center" style="margin-top: 20px;">
          <span class="mdui-chip-icon mdui-color-blue"><i class="mdui-icon material-icons">&#xe87c;</i></span>
          <span class="mdui-chip-title">验票成功.</span>
        </div>
        <%= image_tag("bluefairy2.jpg") %>
      </div>
    <% else %>
      <div class="mdui-center">
        <div class="mdui-chip mdui-center" style="margin-top: 20px;">
          <span class="mdui-chip-icon mdui-color-blue"><i class="mdui-icon material-icons">&#xe87c;</i></span>
          <span class="mdui-chip-title">该票已经使用.</span>
        </div>
        <%= image_tag("bluefairy1.jpg") %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/m/user_membership_cards/index.html.erb
<%= wechat_config_js debug: false, api: %w(hideMenuItems closeWindow chooseWXPay) -%>
<script type="application/javascript">
  wx.ready(function() {
    wx.hideOptionMenu();
  });
</script>
<div class="mdui-container">
  <ul class="list-unstyled bfui-membership-card-list">
    <% @user_membership_cards.each_with_index do |user_card, index| %>
    <li>
        <div class="bfui-stamp bfui-stamp-<%= index + 1 %>">
            <div class="par">
                <p>蓝精灵 <%= user_card.membership_card.name %></p>
                <sub class="sign">￥</sub>
                <span><%= user_card.membership_card.fee %></span>
            </div>
            <div class="action">
                <% if user_card.pending? %>
                <a href="javascript:;" onclick="wxpay(this)" data-pid="<%= user_card.id %>" data-pname="<%= user_card.class.name %>" class="mdui-btn">支付</a>
                <% elsif user_card.checkouted? %>
                <a href="<%= m_user_membership_card_path(user_card) %>" class="mdui-btn">查看</a>
                <% elsif user_card.disable? %>
                <a href="<%= m_user_membership_card_path(user_card) %>" class="mdui-btn">已用完</a>
                <% end %>
            </div>
        </div>
    </li>
    <% end %>
  </ul>
</div>
<% if Figaro.env.wechat_pay_mch_id %>
<script>
  function wxpay(e) {
    var pid = $(e).data('pid');
    var pname = $(e).data('pname');
    $.post('/m/wx_pay?id=' + pid + '&name='+ pname, function(data) {
      wx.chooseWXPay({
        timestamp: data.timeStamp,
        nonceStr: data.nonceStr,
        package: data.package,
        signType: data.signType,
        paySign: data.paySign,
        success: function (res) {
          location.reload();
        },
        error: function(e) {
          alert('支付发生错误，请联系客服。');
        }
      });
    });
  }
</script>
<% end %>

app/views/m/user_membership_cards/show.html.erb
<div class="mdui-container">
  <div class="mdui-row-xs-1">
    <div class="mdui-col">
      <div class="mdui-chip mdui-center" style="text-algin:left;margin-top: 20px;">
        <span class="mdui-chip-icon mdui-color-blue"><i class="mdui-icon material-icons">&#xe87c;</i></span>
        <span class="mdui-chip-title">会员卡号：<%= @user_membership_card.trade_no %></span>
      </div>
      <div class="mdui-chip mdui-center" style="text-algin:left;margin-top: 20px;">
        <span class="mdui-chip-icon mdui-color-blue"><i class="mdui-icon material-icons">&#xe87c;</i></span>
        <span class="mdui-chip-title">总次数：<%= @user_membership_card.membership_card.count %></span>
      </div>
      <div class="mdui-chip mdui-center" style="text-algin:left;margin-top: 20px;margin-bottom: 20px;">
        <span class="mdui-chip-icon mdui-color-blue"><i class="mdui-icon material-icons">&#xe87c;</i></span>
        <span class="mdui-chip-title">使用次数：<%= @user_membership_card.count %></span>
      </div>
    </div>
  </div>
  <div class="mdui-row">
    <div class="mdui-col-xs-12">
      <button id="user_membership_card_qrcode" class="mdui-btn mdui-color-pink-accent mdui-btn-raised mdui-btn-block mdui-ripple">显示二维码</button>
    </div>
  </div>
</div>
<div class="bfui-dialog-box" id="qrcode-dialog">
  <div class="bfui-dialog">
    <div class="bfui-dialog-title">向工作人员出示验证码</div>
    <div class="bfui-dialog-content">
      <div id="qrcode"></div>
    </div>
    <div class="bfui-dialog-actions">
      <button onclick="javascript:$('#qrcode-dialog').hide();" class="mdui-btn mdui-color-pink-accent mdui-btn-raised mdui-ripple">关闭</button>
    </div>
  </div>
</div>
<script>
  $('#user_membership_card_qrcode').click(function() {
    $('#qrcode').empty();
    $('#qrcode').qrcode("http://bluefairypark.cn/m/user_membership_cards/<%= @user_membership_card.id %>/check");
    $('#qrcode-dialog').show();
  });
</script>