config/routes.rb
Rails.application.routes.draw do

  get 'auth/wechat/callback' => 'users#omniauth_callbacks'

  namespace :m do
    get 'home/index'
    get 'home/water'

    get 'fairy_coins_pay' => 'pay#fairy_coins_pay'
    post 'wx_pay' => 'pay#wx_pay'
    post 'wx_notify' => 'pay#wx_notify'

    resources :crowdfundings
    #resources :coupons, only: [:new, :create]
    #resources :awards, only: [:index, :show]
    #resources :lucky_draws, only: [:index, :create] do
    #  collection do
    #    get :draw
    #    get :list
    #  end
    #end
    resources :user_lockers, only: [:new, :create]
    resources :membership_cards, only: [:index, :show, :new]
    resources :user_membership_cards, only: [:index, :show, :create] do
      member do
        get :check
        post :checkin
      end
    end
    resources :deposits, only: [:index, :show, :new, :create]
    resources :orders, only: [:index, :show, :create]
    resources :order_tickets, only: [] do
      member do
        get :check
        post :checkin
      end
    end
    resources :tickets, only: [:index, :show]
    resources :shopping_carts, only: [:index, :destroy] do
      collection do
        get :add
      end
    end
    resources :users do
      collection do
        get :profile
        get :foregift
      end
    end
    resources :lessons, only: [:index, :show] do
      resources :students, only: [:new, :create]
    end
    resources :students, only: [:index, :show]
  end

  get 'home/index'

  namespace :admin do
    scope "/park" do
      resources :orders, only: [:index, :show, :create, :destroy]
      resources :order_tickets, only: [:show, :edit, :update]
      resources :coupons
      resources :awards
      resources :user_lockers, only: [:index] do
        member do
          get :back
        end
      end
      resources :lockers
      resources :membership_cards do
        resources :user_membership_cards
      end
      resources :users, only: [:index]
      resources :tickets do
        collection do
          get :sell
        end
      end
    end
    scope '/lesson' do
      resources :daylines do
        member do
          get :notice
          get :congratulate
        end
      end
      resources :timelines
      resources :lessons do
        member do
          get :subitems
        end
      end
      resources :students
    end
    scope '/store' do
      resources :products
      resources :sales_lists
    end
    scope '/system' do
      resources :admins
      resources :roles
      resources :crowdfundings
    end
    
    resources :sessions, only: [:new, :create, :destroy]
    
    resources :games do
      member do
        get :lot
        get :lock
      end
      resources :playeds do
        resources :techstats, only: [:index, :create, :edit, :update]
      end
      resources :game_teams, only: [:index, :new, :create, :edit, :update]
    end

    get 'dashboard/index'
    root "dashboard#index"
  end

  root "home#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password

  belongs_to :role, optional: true
  has_many :permissions, through: :role
end

app/models/award.rb
class Award < ApplicationRecord
    has_many :lucky_draws
end

app/models/coupon.rb
class Coupon < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :ticket
end

app/models/dayline.rb
class Dayline < ApplicationRecord
    has_many :students
    belongs_to :lesson
end

app/models/deposit.rb
class Deposit < ApplicationRecord
    belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    has_many :students
    has_many :daylines
    has_many :timelines
end

app/models/locker.rb
class Locker < ApplicationRecord
    enum state: [:used, :unused, :maintained]
    
    has_many :user_lockers
end

app/models/lucky_draw.rb
class LuckyDraw < ApplicationRecord
    belongs_to :user
    belongs_to :award, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
    enum status: [:pending, :checkouted, :completed]

    has_many :order_tickets, :dependent => :destroy
    belongs_to :user

    def total_price
        total_price = 0
        self.order_tickets.each do |order_ticket|
            total_price += order_ticket.ticket.price
        end
        total_price
    end
    
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :role
  has_many :admins, through: :role

  validates :resource, presence: true
  validates :action, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :sales_list_products
end

app/models/role.rb
class Role < ApplicationRecord
  RESERVED = %w(admin)

  has_many :permissions, dependent: :destroy
  has_many :admins

  validates :name, presence: true, uniqueness: true

  scope :editable, -> { where.not(name: RESERVED ) }
end

app/models/sales_list.rb
class SalesList < ApplicationRecord
    has_many :sales_list_products

    def total_price
        total_price = 0
        self.sales_list_products.each do |sales_list_product|
            total_price += sales_list_product.product.price
        end
        total_price
    end
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
  load! if Rails.env.development?
end

app/models/student.rb
class Student < ApplicationRecord
    enum status: [:pending, :checkouted, :completed, :canceled]

    belongs_to :lesson
    belongs_to :user, optional: true
    belongs_to :dayline
    belongs_to :timeline
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :order_tickets
  has_many :shopping_carts
  has_many :coupons
end

app/models/timeline.rb
class Timeline < ApplicationRecord
    has_many :students
    belongs_to :lesson
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  extend Enumerize  #pending 新建状态  cooking烹饪状态  finished完成状态  canceled取消
  enumerize :position,     in: [:PG, :SG, :SF, :PF, :C], default: :SF

  enum sex: [:unknown, :female, :male]

  mount_uploader :avatar, UserAvatarUploader
  attr_accessor :uploader_secure_token

  has_one :my_team, class_name: "Team"
  belongs_to :team
  has_many :techstats
  has_many :shopping_carts
  has_many :orders
  has_many :students
  has_many :deposits
  has_many :user_membership_cards
  has_many :user_lockers
  has_many :lucky_draws
  has_many :coupons
  has_many :user_crowdfundings

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.nickname = auth.info.nickname
      user.sex = auth.info.sex
      user.wechat_avatar = auth.info.headimgurl
      user.open_id = auth.info.openid
    end
  end
end

app/models/user_locker.rb
class UserLocker < ApplicationRecord
    belongs_to :user
    belongs_to :locker
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/admins/_form.html.erb
<%= form_for [:admin, @admin], html: { class: "form-horizontal" } do |f| %>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">员工名称</label>
        <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control", placeholder: "员工真名" %>
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">联系电话</label>
        <div class="col-sm-10">
            <%= f.text_field :phone, class: "form-control", placeholder: "手机号码" %>
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">登录密码</label>
        <div class="col-sm-10">
            <%= f.password_field :password, class: "form-control", placeholder: "密码" %>
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">密码确认</label>
        <div class="col-sm-10">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "再次输入密码" %>
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">报班</label>
        <div class="col-sm-10">
            <% Role.all.each do |role| %>
            <label class="radio-inline">
                <%= f.radio_button :role_id, role.id %> <%= role.name %>
            </label>
            <% end %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">保存</button>
        </div>
    </div>
<% end %>

app/views/admin/admins/index.html.erb
<div class="card">
  <div class="card-body card-padding">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>员工名称</th>
                <th>联系电话</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        <% @admins.each do |admin| %>
            <tr>
                <th scope="row"><%= admin.id %></th>
                <td><%= admin.name %></td>
                <td><%= admin.phone %></td>
                <td>
                    <%= link_to "修改", edit_admin_admin_path(admin) %>
                </td>
            </tr>
        <% end %>
    </table>
  </div>
</div>